name: capture-rating-graphs
on:
  push:
  schedule:
    - cron: "0 3 * * *"
jobs:
  capture-rating-graphs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Run python
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          python capture-rating-graphs.py
      - name: Commit and Push
        run: |
          git add -n rating-graph-algorithm.png rating-graph-heuristic.png
          if ! git diff --exit-code --quiet
          then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add rating-graph-algorithm.png rating-graph-heuristic.png
            git commit -m "Update rating graphs"
            git push origin main
          fi
